### ISSUE TITLE
Adding analytics to the Distiller 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#31]
## Acceptance criteria
- [ ] DAP 

## Implementation notes
- [ ] @cantsin will provide steps in the process

**Comment by cantsin** [comment]
Update: DAP instructions are at https://github.com/digital-analytics-program/gov-wide-code -- basically the same thing as Google Analytics: all we'd need to do is add a `script` tag. Still working on getting the agency ref id, should have an update by tomorrow (Tuesday afternoon, Pacific time).

**Comment by cantsin** [comment]
Turns out that the query parameter `agency=GSA` is all we need to add, but also working on getting internal access so we can see the results. Apparently activity on analytics.usa.gov only shows up if there are more than 10 results (for reasons of anonymity).

@danielnaab while we're waiting, let's go ahead and add a script tag in the base Django template: 

```html
<!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA" id="_fed_an_ua_tag"></script>
```
